### ISSUE TITLE
ICS Calendar Export - URL starts with "localhost"

### ISSUE THREAD

**Issue by NoamElul** [pennlabs/penn-courses#488]
The URL shown to download the ICS calendar starts with "http://localhost:3000/" instead of the PennCoursePlan URL. 

![image](https://user-images.githubusercontent.com/77859709/232838308-6341faab-14d0-47ee-9427-62d903aa4fde.png)

I got it to work by manually replacing "http://localhost:3000/" in the URL with "https://penncourseplan.com/" , and was able to download the calendar properly. 

EDIT: However, I'm sometimes getting a Server Error 500 on the download page.

**Comment by andyjiang3** [comment]
Thanks, this is fixed now. We are looking into the 500 server error.
