### ISSUE TITLE
[PDP] Allow easier feedback for beta users

### ISSUE THREAD

**Issue by yuntongf** [pennlabs/penn-courses#654]
- Embed a google form or Airtable form link?
- Provide easy ways for the user to report bugs: the user flow that lead to the bug, a screen shot of the bug, and how much do they think this affects their user experience

**Comment by AaDalal** [comment]
I think I fixed by linting this form: https://airtable.com/appFRa4NQvNMEbWsA/shr120VUScuNJywyv
